INSERT INTO student (name) VALUES ('眼膏');
INSERT INTO student (name) VALUES ('守递');
INSERT INTO student (name) VALUES ('天天');
INSERT INTO student (name) VALUES ('向上');
INSERT INTO student (name) VALUES ('好好');
INSERT INTO student (name) VALUES ('学习');

INSERT INTO score (student_id, lesson, score) VALUES (1,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (1,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (1,'外语',55);
INSERT INTO score (student_id, lesson, score) VALUES (2,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (2,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (2,'外语',55);
INSERT INTO score (student_id, lesson, score) VALUES (3,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (3,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (3,'外语',55);
INSERT INTO score (student_id, lesson, score) VALUES (4,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (4,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (4,'外语',55);
INSERT INTO score (student_id, lesson, score) VALUES (5,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (5,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (5,'外语',55);
INSERT INTO score (student_id, lesson, score) VALUES (6,'语文',55);
INSERT INTO score (student_id, lesson, score) VALUES (6,'数学',55);
INSERT INTO score (student_id, lesson, score) VALUES (6,'外语',55);
